using YouTubeApiCleanArchitecture.Application.Abstraction.Messaging.Queries;

namespace YouTubeApiCleanArchitecture.Application.Features.Customers.Queries.GetAllCustomers;
public class GetAllCustomersQuery : IQuery<CustomerResponseCollection>;